### PR TITLE
don't install hooks if DONT_INSTALL_HUSKY_HOOKS is set

### LINKED ISSUE #8: Add a way to not add hooks during tests
It'd be nice if there was something like `DONT_INSTALL_HUSKY_HOOKS` to not install hooks when `cargo test` is run.

Related: https://github.com/Cogitri/gxi/issues/199

### PR DESCRIPTION
**Pull request by Cogitri**
fixes #8

### CODE REVIEW

**Comment by Cogitri** [comment]
Thank you :)

**Comment by rhysd** [comment]
@Cogitri I'm sorry for late response. I'll soon publish new version.

**Comment by rhysd** [comment]
@Cogitri Let me rename the environment variable to `$CARGO_HUSKY_DONT_INSTALL_HOOKS` to explicitly indicate the variable is related to cargo-husky.

**Comment by Cogitri** [comment]
No worries, thank you for your work! :)

Sure, renaming it sounds OK, just be sure to mention it in the release notes :)

**Comment by rhysd** [comment]
New version v1.4.0 was released. The environment variable is mentioned [here](https://github.com/rhysd/cargo-husky#ignore-installing-hooks).

**Pull request merged**
